Repository boostcampwm-2022/web33-Mildo, pull requests merged in 2022-12, with the labels that each got.

#56 PR : dev <- Feature/login
  client/package.json
  client/src/apis/apis.ts
  client/src/atom/infoDetail.ts
  client/src/atom/loginModal.ts
  client/src/atom/myInfoSideBar.ts
  client/src/components/LoginModal/LoginModal.tsx
  client/src/components/ModalFilter/ModalFilter.tsx
  client/src/components/MyInfoSideBar/MyInfoSideBar.tsx
  client/src/components/SearchBarAndMyBtn/SearchBarAndMyBtn.tsx
  client/src/config/constants.ts
  client/src/pages/MainPage/MainPage.tsx
  client/src/utils/button.util.ts
  client/src/utils/login.util.ts
  client/src/utils/map.util.ts
  client/yarn.lock
  server/package.json
  server/src/apis/controllers/auth.controller.ts
  server/src/apis/controllers/naver.controller.ts
  server/src/apis/index.ts
  server/src/apis/middlewares/auth.middleware.ts
  server/src/apis/models/User.ts
  server/src/apis/passport/index.ts
  server/src/apis/passport/naverStrategy.ts
  server/src/apis/routers/auth.router.ts
  server/src/apis/routers/naver.router.ts
  server/src/apis/types/interfaces.ts
  server/src/app.ts
  server/yarn.lock
Labels: 🖥Frontend, ⚙Backend, 🕹Featrue, 🛠Fix, 🇰🇷윤우, ✂Refactor, 😁상준

#76 리액트 쿼리로 캐싱 기능 적용
  client/package.json
  client/src/App.tsx
  client/src/atom/infoDetail.ts
  client/src/components/InfoDetailModal/InfoDetailModal.tsx
  client/src/components/SecondLevelComponent/SecondLevelComponent.tsx
  client/src/config/constants.ts
  client/src/hooks/useGraphInfo.tsx
  client/src/types/interfaces.ts
  client/yarn.lock
Labels: 🖥Frontend, 🕹Featrue, 🤯현정

#75 Feature/bookmark
  client/src/apis/apis.ts
  client/src/atom/areasInfo.ts
  client/src/atom/infoDetail.ts
  client/src/atom/userInfo.ts
  client/src/components/InfoDetailModal/InfoDetailModal.style.tsx
  client/src/components/InfoDetailModal/InfoDetailModal.tsx
  client/src/components/Map/Map.tsx
  client/src/components/Modal/Modal.tsx
  client/src/components/MyInfoSideBar/MyInfoSideBar.tsx
  client/src/config/constants.ts
  client/src/pages/MainPage/MainPage.tsx
  client/src/types/interfaces.ts
  server/src/apis/controllers/auth.controller.ts
  server/src/apis/models/User.ts
  server/src/apis/passport/naverStrategy.ts
  server/src/apis/repositories/auth.repository.ts
  server/src/apis/routers/auth.router.ts
  server/src/apis/services/auth.service.ts
  server/src/apis/types/interfaces.ts
Labels: 🖥Frontend, ⚙Backend, 🕹Featrue, 👦🏻한빈

#77 PR : dev <- Feature/search area
  client/src/apis/apis.ts
  client/src/components/RelatedAreaItem/RelatedAreaItem.tsx
  client/src/components/RelatedAreaList/RelatedAreaList.tsx
  client/src/components/SearchBarAndMyBtn/SearchBarAndMyBtn.tsx
  client/src/config/constants.ts
  client/src/utils/search.util.ts
  server/src/apis/controllers/seoul.controller.ts
  server/src/apis/repositories/area.repository.ts
  server/src/apis/repositories/area.ropository.ts
  server/src/apis/routers/seoul.router.ts
  server/src/apis/services/area.service.ts
Labels: 🖥Frontend, ⚙Backend, 🕹Featrue, 🇰🇷윤우

#78 dev <- Feature/filter marker,logout,styling modal
  client/src/App.tsx
  client/src/atom/densityFilterBtn.ts
  client/src/atom/markerArray.ts
  client/src/components/DensityFilterList/DensityFilterList.tsx
  client/src/components/DensityFilterListBtn/DensityFilterListBtn.tsx
  client/src/components/InfoDetailModal/InfoDetailModal.style.tsx
  client/src/components/Map/Map.tsx
  client/src/components/MyInfoSideBar/MyInfoSideBar.tsx
  client/src/components/SearchBarAndMyBtn/SearchBarAndMyBtn.tsx
  client/src/config/constants.ts
  client/src/hooks/useMarker.ts
  client/src/pages/MainPage/MainPage.tsx
  client/src/types/interfaces.ts
  server/src/apis/controllers/naver.controller.ts
  server/src/apis/routers/naver.router.ts
Labels: 🖥Frontend, ⚙Backend, 🕹Featrue, 😁상준

#84 Refactor/search,bookmark,click
  client/src/apis/apis.ts
  client/src/components/InfoDetailModal/InfoDetailModal.style.tsx
  client/src/components/InfoDetailModal/InfoDetailModal.tsx
  client/src/components/Map/Map.tsx
  client/src/components/MyInfoSideBar/MyInfoSideBar.tsx
  client/src/components/RelatedAreaItem/RelatedAreaItem.tsx
  client/src/components/RelatedAreaList/RelatedAreaList.tsx
  client/src/components/SecondLevelComponent/SecondLevelComponent.tsx
  client/src/config/constants.ts
  client/src/hooks/useGraphInfo.tsx
  client/src/types/interfaces.ts
  client/src/utils/time.util.ts
Labels: 🖥Frontend, ✂Refactor, 👦🏻한빈

#85 Refactor/search area
  client/src/atom/relatedAreaList.ts
  client/src/components/Map/Map.tsx
  client/src/components/RelatedAreaItem/RelatedAreaItem.tsx
  client/src/components/RelatedAreaList/RelatedAreaList.tsx
  client/src/components/SearchBarAndMyBtn/SearchBarAndMyBtn.tsx
  client/src/config/constants.ts
  client/src/hooks/useGraphInfo.ts
Labels: 🖥Frontend, 🇰🇷윤우, ✂Refactor

#88 Refactor/client apis
  client/package.json
  client/public/index.html
  client/src/App.tsx
  client/src/apis/apis.ts
  client/src/atom/areasInfo.ts
  client/src/atom/userInfo.ts
  client/src/components/InfoDetailModal/InfoDetailModal.tsx
  client/src/components/Map/Map.tsx
  client/src/components/MapLoading/MapLoading.tsx
  client/src/components/MyInfoSideBar/MyInfoSideBar.tsx
  client/src/components/SearchBarAndMyBtn/SearchBarAndMyBtn.tsx
  client/src/components/SecondLevelComponent/SecondLevelComponent.style.tsx
  client/src/components/SecondLevelComponent/SecondLevelComponent.tsx
  client/src/config/constants.ts
  client/src/hooks/useGraphInfo.ts
  client/src/hooks/useMarker.ts
  client/src/pages/MainPage/MainPage.tsx
  client/src/types/interfaces.ts
  client/src/utils/graph.util.ts
  client/src/utils/time.util.ts
  client/yarn.lock
  server/src/apis/controllers/auth.controller.ts
  server/src/apis/middlewares/auth.middleware.ts
  server/src/apis/routers/naver.router.ts
Labels: 🖥Frontend, ⚙Backend, 🕹Featrue, 🇰🇷윤우, ✂Refactor, 🤯현정

#89 Feature/UI issue
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/src/App.tsx
  client/src/components/InfoDetailModal/InfoDetailModal.style.tsx
  client/src/components/InfoDetailModal/InfoDetailModal.tsx
  client/src/components/Modal/Modal.tsx
  client/src/components/RelatedAreaList/RelatedAreaList.tsx
  client/src/components/SearchBarAndMyBtn/SearchBarAndMyBtn.tsx
  client/src/components/SecondLevelComponent/SecondLevelComponent.style.tsx
  client/src/config/constants.ts
  client/src/types/interfaces.ts
Labels: 🖥Frontend, 🎨Style, 😁상준

#101 Test/vite 브랜치 dev로 병합
  client/index.html
  client/package.json
  client/src/App.tsx
  client/src/apis/apis.ts
  client/src/components/InfoDetailModal/InfoDetailModal.tsx
  client/src/components/LoginModal/LoginModal.tsx
  client/src/components/Map/Map.tsx
  client/src/components/MyInfoSideBar/MyInfoSideBar.tsx
  client/src/pages/MainPage/MainPage.tsx
  client/src/vite-env.d.ts
  client/vite.config.ts
  client/yarn.lock
Labels: 🖥Frontend, ✂Refactor, 👦🏻한빈

#105 PR: dev <- fix : redis에서 못 가져올 경우 mongo에서 가져오기
  client/yarn.lock
  server/src/apis/controllers/seoul.controller.ts
  server/src/apis/repositories/population.repository.ts
  server/src/apis/services/redis.service.ts
  server/src/apis/services/seoul.service.ts
Labels: ⚙Backend, 🛠Fix, 🇰🇷윤우

#106 [#104] fix : 변수 수정 및 try-catch 삭제
  server/src/apis/controllers/seoul.controller.ts
Labels: ⚙Backend, 🛠Fix, 🇰🇷윤우
